package com.devmadhurendra.assignment;

public interface AmazonTestConstants {
    String AMAZON_URI = "https://www.amazon.in";
    String TODAY_DEAL_XPATH = "//a[@href='/deals?ref_=nav_cs_gb']";
    // String TOP_3_RD_DEAL = "/html/body/div[1]/div[1]/div[15]/div/div/div/div[3]/div[3]/div/div[3]";
    // String TOP_3_RD_DEAL = "/html/body/div[1]/div[1]/div[12]/div/div/div/div/div/div[2]/div/div[3]";
    String TOP_3_RD_DEAL = ".DealGridItem-module__dealItemContent_1vFddcq1F8pUxM8dd9FW32";
    String PRODUCT_TO_BE_ADDED = "/html/body/div[1]/div[2]/div/div[2]/div/div/div[2]/div/div[2]/ul/li[2]/span";
    // String ADD_TO_CART_BUTTON_ELEMENT = "//input[@id='add-to-cart-button']";
    String ADD_TO_CART_BUTTON_ELEMENT = "(//input[@id='add-to-cart-button'])[2]";
    // String CART_BUTTON_ELEMENT = "/html/body/div[8]/div[3]/div[3]/div/div[1]/div[3]/div[1]/div[2]/div[3]/form/span";
    // String CART_BUTTON_ELEMENT = "/html/body/div[1]/header/div/div[1]/div[3]/div/a[4]";
    String CART_BUTTON_ELEMENT = "//input[@aria-labelledby='attach-sidesheet-view-cart-button-announce']";
    String ANOTHER_CART_ELEMENT = "#nav-cart";
    String SKIP_ELEMENT = "/html/body/div[8]/div[3]/div[1]/div/div/div[2]/div[2]/div/div/div[3]/div/span[2]/span/input";
    String PRODUCT_HAVE_TO_ADD_IN_CART = "productTitle";
    String ADDED_ITEM_IN_CART_PRODUCT = "/html/body/div[1]/div[1]/div[3]/div[5]/div/div[2]/div[1]/div/form/div[2]/div[3]/div[4]/div/div[2]/ul/li/span/a/span[1]/span/span[2]";
    String QUANTITY_ELEMENT = "//span[@class='a-dropdown-prompt']";
    String SEARCH_INPUT_ELEMENT = "/html/body/div[1]/header/div/div[1]/div[2]/div/form/div[2]/div[1]/input";
    String VALUE_TO_SEARCH = "Mobiles";
    String ALL_PRODUCTS = "//div[@data-cy='title-recipe']";
    String MOBILES_NAV = "//a[text()='Mobiles']";
    String PROCEED_TO_BUY = "#sc-buy-box-ptc-button";
    String AMAZON_USERNAME = "7780108408";
    String AMAZON_PASSWORD = "Sai@123Amazon";
    String EMAIL_LOGIN = "#ap_email";
    String CONTINUE = "#continue";
    String PASSWORD_LOGIN = "#ap_password";
    String SIGN_IN = "#signInSubmit";
    String ITEM_DELIVERY_DATE = "#spc-orders > div > div > div.a-row.shipment > div > div > div:nth-child(1)";
    String HOME_PAGE = "#footer > div:nth-child(4) > a:nth-child(4)";
    String RETURN_AND_ORDERS = "#nav-orders";
    String SELECT_DROPDOWN = "#a-autoid-1";
    String SELECT_PAST_ONE_YEAR = "#time-filter_3";
    String ORDERS_IN_ONE_YEAR = "#a-page > section > div > div.a-row.a-spacing-base > form > label > span";
    String YOUR_ACCOUNTS = "#nav-link-accountList > span";
    String YOUR_ACCOUNT = "#nav-al-your-account > a:nth-child(2)";
    String ADDRESS_COLUMN = ".address-column";
    String YOUR_ADDRESSES = "#a-page > div.a-container > div > div:nth-child(3) > div:nth-child(1) > a > div";
    String ADD_ADDRESS = "#ya-myab-address-add-link > div";
    String FULL_NAME = "#address-ui-widgets-enterAddressFullName";
    String MOBILE_NUMBER = "#address-ui-widgets-enterAddressPhoneNumber";
    String PIN_CODE = "#address-ui-widgets-enterAddressPostalCode";
    String ADDRESS_LINE_1 = "#address-ui-widgets-enterAddressLine1";
    String ADDRESS_LINE_2 = "#address-ui-widgets-enterAddressLine2";
    String LANDMARK = "#address-ui-widgets-landmark";
    String TOWN_CITY = "#address-ui-widgets-enterAddressCity";
    String CHOOSE_CITY = "#address-ui-widgets-enterAddressStateOrRegion > span > span";
    String UTTAR_PRADESH = "#address-ui-widgets-enterAddressStateOrRegion-dropdown-nativeId_33";
    String ADD_ADDRESS_BUTTON = "#address-ui-widgets-form-submit-button > span > input";
    String FULL_NAME_VALUE = "Madhurendra Nath Tiwari";
    String MOBILE_NUMBER_VALUE = "6307233230";
    String PIN_CODE_VALUE = "272175";
    String ADDRESS_LINE_1_VALUE = "Khalilabad Sant Kabir Nagar";
    String ADDRESS_LINE_2_VALUE = "Vidhiyani Gorkhal";
    String LANDMARK_VALUE = "Near Divya library";
    String TOWN_CITY_VALUE = "Khalilabad";
    String PAYMENT_OPTIONS = "#a-page > div.a-container > div > div:nth-child(3) > div:nth-child(3) > a > div";
    String EDIT_PAYMENT = "#walletWebsiteContainer > div.a-section.bottomNavPanelSection > div:nth-child(2) > div > a";
    String YOUR_ACCOUNT_TREE = "#a-page > div.a-section > div > div.a-section.a-spacing-medium > div > ul > li:nth-child(1) > span > a";
}
